In [1]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy

In [2]:
data = pd.read_csv("..//..//dataset//oakland-crime-statistics-2011-to-2016//records-for-2014.csv")
print(data)

       Agency              Create Time  Area Id Beat  Priority  \
0          OP  2014-01-01T00:00:00.000      1.0  02X         2
1          OP  2014-01-01T00:00:00.000      2.0  26Y         2
2          OP  2014-01-01T00:00:00.000      2.0  30Y         2
3          OP  2014-01-01T00:00:00.000      2.0  30Y         2
4          OP  2014-01-01T00:01:04.000      2.0  35X         2
5          OP  2014-01-01T00:01:08.000      2.0  32X         2
6          OP  2014-01-01T00:01:23.000      2.0  31Z         2
7          OP  2014-01-01T00:01:31.000      2.0  23X         2
8          OP  2014-01-01T00:01:40.000      1.0  02Y         2
9          OP  2014-01-01T00:02:10.000      2.0  35X         2
10         OP  2014-01-01T00:03:10.000      2.0  29X         2
11         OP  2014-01-01T00:04:13.000      1.0  06X         2
12         OP  2014-01-01T00:04:34.000      2.0  23X         2
13         OP  2014-01-01T00:04:48.000      2.0  32Y         2
14         OP  2014-01-01T00:05:09.000      2.0  32X         2
15         OP  2014-01-01T00:06:06.000      1.0  10X         2
16         OP  2014-01-01T00:06:25.000      1.0  22Y         2
17         OP  2014-01-01T00:06:29.000      2.0  27X         1
18         OP  2014-01-01T00:06:53.000      1.0  09X         2
19         OP  2014-01-01T00:06:59.000      1.0  17Y         2
20         OP  2014-01-01T00:07:04.000      1.0  05X         1
21         OP  2014-01-01T00:07:36.000      2.0  27X         2
22         OP  2014-01-01T00:07:38.000      2.0  31Z         2
23         OP  2014-01-01T00:08:40.000      2.0  27Y         2
24         OP  2014-01-01T00:09:04.000      2.0  27Y         2
25         OP  2014-01-01T00:10:05.000      1.0  15X         2
26         OP  2014-01-01T00:11:55.000      1.0  09X         2
27         OP  2014-01-01T00:12:40.000      2.0  25X         2
28         OP  2014-01-01T00:13:20.000      2.0  35X         2
29         OP  2014-01-01T00:15:29.000      1.0  13Z         2
...       ...                      ...      ...  ...       ...
187450     OP  2014-10-29T19:01:28.000      NaN  NaN         1
187451     OP  2014-10-30T22:00:29.000      NaN  18Y         2
187452     OP  2014-11-03T20:47:30.000      NaN  20X         1
187453     OP  2014-11-03T07:48:56.000      NaN  04X         2
187454     OP  2014-11-03T07:45:01.000      NaN  22Y         2
187455     OP  2014-11-04T18:56:19.000      NaN  24X         2
187456     OP  2014-11-03T20:48:57.000      NaN  24Y         1
187457     OP  2014-11-03T07:39:01.000      NaN  17Y         2
187458     OP  2014-11-03T20:50:20.000      NaN  03X         1
187459     OP  2014-11-13T12:09:58.000      NaN  35X         2
187460     OP  2014-11-12T12:02:25.000      NaN  06X         2
187461     OP  2014-11-12T12:01:53.000      NaN  29X         2
187462     OP  2014-11-08T22:42:49.000      NaN  04X         2
187463     OP  2014-11-08T22:44:40.000      NaN  12Y         2
187464     OP  2014-11-09T11:28:01.000      NaN  NaN         1
187465     OP  2014-11-26T21:22:03.000      NaN  27Y         1
187466     OP  2014-11-26T21:23:46.000      NaN  21X         2
187467     OP  2014-11-13T12:11:22.000      NaN  21X         2
187468     OP  2014-11-14T08:00:06.000      NaN  35Y         2
187469     OP  2014-11-14T13:35:31.000      NaN  13X         2
187470     OP  2014-11-19T12:14:19.000      NaN  NaN         2
187471     OP  2014-11-18T18:30:13.000      NaN  08X         1
187472     OP  2014-11-18T13:00:39.000      NaN  06X         1
187473     OP  2014-11-21T20:12:14.000      NaN  NaN         2
187474     OP  2014-11-21T09:01:50.000      NaN  08X         2
187475     OP  2014-12-30T05:59:53.000      NaN  07X         1
187476     OP  2014-10-28T21:05:21.000      NaN  02X         1
187477     OP  2014-11-03T07:14:40.000      NaN  23X         2
187478     OP  2014-10-20T09:45:52.000      NaN  16Y         1
187479     OP  2014-11-12T01:30:19.000      NaN  07X         2

       Incident Type Id Incident Type Description     Event Number  \
0                 415GS              415 GUNSHOTS  LOP140101000001
1                 415GS              415 GUNSHOTS  LOP140101000002
2                 415GS              415 GUNSHOTS  LOP140101000004
3                 415GS              415 GUNSHOTS  LOP140101000005
4                 CODE7      SUBJECT ARMED WITH W  LOP140101000010
5                 415GS              415 GUNSHOTS  LOP140101000006
6                 415GS              415 GUNSHOTS  LOP140101000007
7                  911H               911 HANG-UP  LOP140101000008
8                 415GS              415 GUNSHOTS  LOP140101000009
9                 415GS              415 GUNSHOTS  LOP140101000011
10                415GS              415 GUNSHOTS  LOP140101000017
11                  247       SHOOTING AT/INTO AN  LOP140101000014
12                415GS              415 GUNSHOTS  LOP140101000012
13                415GS              415 GUNSHOTS  LOP140101000013
14                415GS              415 GUNSHOTS  LOP140101000015
15                 933R              ALARM-RINGER  LOP140101000016
16                 911H               911 HANG-UP  LOP140101000018
17                CODE7      SUBJECT ARMED WITH W  LOP140101000024
18                 933R              ALARM-RINGER  LOP140101000023
19                 415C               415 UNKNOWN  LOP140101000019
20                  929                      FIRE  LOP140101000020
21                415GS              415 GUNSHOTS  LOP140101000021
22                415GS              415 GUNSHOTS  LOP140101000022
23                415GS              415 GUNSHOTS  LOP140101000027
24                415GS              415 GUNSHOTS  LOP140101000025
25                415GS              415 GUNSHOTS  LOP140101000026
26                415GS              415 GUNSHOTS  LOP140101000028
27                  912         SUSPICIOUS PERSON  LOP140101000032
28                415GS              415 GUNSHOTS  LOP140101000033
29                  HAZ      HAZARDOUS SITUATION/  LOP140101000039
...                 ...                       ...              ...
187450              943                     FIGHT  LOP141029001022
187451              922       DRUNK ON THE STREET  LOP141030001083
187452             PDOA      POSSIBLE DEAD PERSON  LOP141103000917
187453           HYDRNT              OPEN HYDRANT  LOP141103000175
187454             601I      INCORRIGIBLE: BEYOND  LOP141103000173
187455            415BF             415 BOYFRIEND  LOP141104000927
187456             SUSP                   SUSPECT  LOP141103000918
187457             955A            VICIOUS ANIMAL  LOP141103000171
187458              918          PERSON SCREAMING  LOP141103000920
187459             955A            VICIOUS ANIMAL  LOP141113000497
187460             5150              MENTALLY ILL  LOP141112000450
187461             933R              ALARM-RINGER  LOP141112000448
187462            415GS              415 GUNSHOTS  LOP141108001015
187463             415C               415 UNKNOWN  LOP141108001017
187464              945       AMBULANCE FOLLOW UP  LOP141109000388
187465              910           PROWLER OUTSIDE  LOP141126000831
187466            10851            STOLEN VEHICLE  LOP141126000833
187467            20002       HIT & RUN (PROPERTY  LOP141113000498
187468             EVID                  EVIDENCE  LOP141114000216
187469             933R              ALARM-RINGER  LOP141114000556
187470             911H               911 HANG-UP  LOP141119000513
187471            10851            STOLEN VEHICLE  LOP141118000926
187472              487               GRAND THEFT  LOP141118000528
187473             911H               911 HANG-UP  LOP141121000998
187474              975      STAND BY AND PRESERV  LOP141121000318
187475              929                      FIRE  LOP141230000166
187476              245      ASSAULT W/DEADLY WEA  LOP141028001057
187477              HAZ      HAZARDOUS SITUATION/  LOP141103000159
187478             901A      VEHICLE COLLISION-PE  LOP141020000319
187479              240                   ASSAULT  LOP141112000046

                    Closed Time  \
0       2014-01-01T03:22:08.000
1       2014-01-01T02:56:31.000
2       2014-01-01T00:49:53.000
3       2014-01-01T02:51:11.000
4       2014-01-01T05:33:22.000
5       2014-01-01T03:53:57.000
6       2014-01-01T00:01:32.000
7       2014-01-01T08:23:08.000
8       2014-01-01T03:30:10.000
9       2014-01-01T10:35:45.000
10      2014-01-01T03:08:48.000
11      2014-01-01T11:43:10.000
12      2014-01-01T03:23:00.000
13      2014-01-01T02:46:17.000
14      2014-01-01T00:11:30.000
15      2014-01-01T07:38:34.000
16      2014-01-01T00:10:25.000
17      2014-01-01T00:24:49.000
18      2014-01-01T04:37:57.000
19      2014-01-01T08:09:33.000
20      2014-01-01T00:08:34.000
21      2014-01-01T06:58:13.000
22      2014-01-01T11:52:45.000
23      2014-01-01T03:43:12.000
24      2014-01-01T03:23:54.000
25      2014-01-01T03:47:23.000
26      2014-01-01T03:23:09.000
27      2014-01-01T00:53:06.000
28      2014-01-01T01:24:42.000
29      2014-01-01T02:08:09.000
...                         ...
187450  2014-10-29T19:01:28.000
187451  2014-10-30T22:35:49.000
187452  2014-11-03T22:27:40.000
187453  2014-11-03T07:48:59.000
187454  2014-11-03T09:44:38.000
187455  2014-11-04T22:56:39.000
187456  2014-11-04T02:07:27.000
187457  2014-11-03T13:54:44.000
187458  2014-11-03T21:05:45.000
187459  2014-11-14T11:01:10.000
187460  2014-11-12T12:36:13.000
187461  2014-11-12T12:03:38.000
187462  2014-11-08T23:21:41.000
187463  2014-11-08T22:53:11.000
187464  2014-11-09T11:38:51.000
187465  2014-11-26T22:02:19.000
187466  2014-11-26T23:34:56.000
187467  2014-11-13T13:19:11.000
187468  2014-11-14T08:36:54.000
187469  2014-11-14T16:17:03.000
187470  2014-11-19T12:15:59.000
187471  2014-11-18T19:57:31.000
187472  2014-11-18T15:18:42.000
187473  2014-11-21T20:33:14.000
187474  2014-11-21T11:26:21.000
187475  2014-12-30T05:59:53.000
187476  2014-10-28T22:53:01.000
187477  2014-11-03T09:00:40.000
187478  2014-10-20T12:07:29.000
187479  2014-11-12T02:14:09.000

                                               Location 1  Zip Codes
0       {'human_address': '{"address": "LINDEN ST", "c...        NaN
1       {'human_address': '{"address": "AV&INTERNATION...        NaN
2       {'human_address': '{"address": "AV&MACARTHUR B...        NaN
3       {'human_address': '{"address": "MACARTHUR BLVD...        NaN
4       {'human_address': '{"address": "AV&DOWLING ST"...        NaN
5       {'human_address': '{"address": "AV&INTERNATION...        NaN
6       {'human_address': '{"address": "AV&PIPPIN ST",...        NaN
7       {'human_address': '{"address": "E 16TH ST", "c...        NaN
8       {'human_address': '{"address": "ST&WILLOW ST",...        NaN
9       {'human_address': '{"address": "86TH AV", "cit...        NaN
10      {'human_address': '{"address": "AV&MACARTHUR B...        NaN
11      {'human_address': '{"address": "MARTIN LUTHER ...        NaN
12      {'human_address': '{"address": "AV&INTERNATION...        NaN
13      {'human_address': '{"address": "MACARTHUR BLVD...        NaN
14      {'human_address': '{"address": "AV&ROYAL ANN S...        NaN
15      {'human_address': '{"address": "59TH ST", "cit...        NaN
16      {'human_address': '{"address": "MACARTHUR BLVD...        NaN
17      {'human_address': '{"address": "47TH AV", "cit...        NaN
18      {'human_address': '{"address": "HOWE ST", "cit...        NaN
19      {'human_address': '{"address": "10TH AV", "cit...        NaN
20      {'human_address': '{"address": "GRAND AV&MARKE...        NaN
21      {'human_address': '{"address": "AV&SAN CARLOS ...        NaN
22      {'human_address': '{"address": "MOORPARK AV", ...        NaN
23      {'human_address': '{"address": "AV&SEMINARY AV...        NaN
24      {'human_address': '{"address": "AV&WENTWORTH A...        NaN
25      {'human_address': '{"address": "MACARTHUR BLVD...        NaN
26      {'human_address': '{"address": "W MACARTHUR BL...        NaN
27      {'human_address': '{"address": "39TH AV", "cit...        NaN
28      {'human_address': '{"address": "83RD AV", "cit...        NaN
29      {'human_address': '{"address": "BLVD&PARK BLVD...        NaN
...                                                   ...        ...
187450  {'latitude': '42.777598', 'longitude': '-86.10...    12476.0
187451  {'latitude': '39.317858', 'longitude': '-76.61...    27307.0
187452  {'latitude': '30.225607', 'longitude': '-92.37...    21181.0
187453  {'latitude': '27.222444', 'longitude': '-80.39...    11199.0
187454  {'latitude': '45.76034', 'longitude': '-108.51...    23276.0
187455  {'latitude': '43.129903', 'longitude': '-77.65...    27347.0
187456  {'latitude': '27.668478', 'longitude': '-80.42...    22280.0
187457  {'latitude': '37.416078', 'longitude': '-122.1...      315.0
187458  {'latitude': '45.460189', 'longitude': '-98.47...    27204.0
187459  {'latitude': '42.57794', 'longitude': '-87.912...    12442.0
187460  {'latitude': '36.825804', 'longitude': '-119.7...    27979.0
187461  {'latitude': '41.699832', 'longitude': '-70.58...      420.0
187462  {'latitude': '42.290689', 'longitude': '-71.40...    22816.0
187463  {'latitude': '21.282438', 'longitude': '-157.7...     7526.0
187464  {'latitude': '34.299407', 'longitude': '-85.00...    23486.0
187465  {'latitude': '33.019627', 'longitude': '-96.70...     4560.0
187466  {'latitude': '32.66655', 'longitude': '-117.09...    10453.0
187467  {'latitude': '41.457702', 'longitude': '-84.88...     5080.0
187468  {'latitude': '37.217435', 'longitude': '-121.8...    11854.0
187469  {'latitude': '42.370496', 'longitude': '-71.10...    16547.0
187470  {'latitude': '18.383182', 'longitude': '-65.84...    26722.0
187471  {'latitude': '42.472465', 'longitude': '-71.02...     7894.0
187472  {'latitude': '39.942248', 'longitude': '-75.17...     3680.0
187473  {'latitude': '31.223089', 'longitude': '-81.84...    32748.0
187474  {'latitude': '41.676273', 'longitude': '-85.98...    22736.0
187475  {'latitude': '40.664095', 'longitude': '-73.66...    26004.0
187476  {'latitude': '34.128805', 'longitude': '-79.82...    27099.0
187477  {'latitude': '27.917761', 'longitude': '-82.51...     7967.0
187478  {'latitude': '40.774561', 'longitude': '-73.90...    16862.0
187479  {'latitude': '37.953895', 'longitude': '-121.2...    12234.0

[187480 rows x 11 columns]

#### 1. 删除空值处理

In [3]:
#删除所有属性中有空值的行
data1 = data.dropna()
print(data1)

Empty DataFrame
Columns: [Agency, Create Time, Area Id, Beat, Priority, Incident Type Id, Incident Type Description, Event Number, Closed Time, Location 1, Zip Codes]
Index: []

#### 2. 用最高频率值进行填充

In [4]:
data2 = copy.deepcopy(data)#拷贝原数据集用于填充
for i in range(10):
    count = data2.iloc[:,i].value_counts()  #依次获取每一列的series
    name = pd.DataFrame(data2.iloc[:,i]).columns.values.tolist()
    sort_ans = count.sort_values(ascending = False) #对各类别的频数值进行排序 并选择最高频率的索引
    fre = sort_ans.index[0]
    fre = str(fre)
    print(name[0]+"的最高频率值为"+fre+'\n')
    
    data2[name[0]] = data2[name[0]].fillna(fre) #进行缺失值的填充
print("------------------------------------------"+'\n'+"填充完毕")

Agency的最高频率值为OP

Create Time的最高频率值为2014-10-14T02:45:12.000

Area Id的最高频率值为1.0

Beat的最高频率值为04X

Priority的最高频率值为2

Incident Type Id的最高频率值为933R

Incident Type Description的最高频率值为ALARM-RINGER

Event Number的最高频率值为LOP140627000103

Closed Time的最高频率值为2014-06-04T16:31:09.000

Location 1的最高频率值为{'human_address': '{"address": "INTERNATIONAL BLVD", "city": "", "state": "", "zip": ""}'}

------------------------------------------
填充完毕

In [5]:
print(data2)  #填充结果

       Agency              Create Time Area Id Beat  Priority  \
0          OP  2014-01-01T00:00:00.000       1  02X         2
1          OP  2014-01-01T00:00:00.000       2  26Y         2
2          OP  2014-01-01T00:00:00.000       2  30Y         2
3          OP  2014-01-01T00:00:00.000       2  30Y         2
4          OP  2014-01-01T00:01:04.000       2  35X         2
5          OP  2014-01-01T00:01:08.000       2  32X         2
6          OP  2014-01-01T00:01:23.000       2  31Z         2
7          OP  2014-01-01T00:01:31.000       2  23X         2
8          OP  2014-01-01T00:01:40.000       1  02Y         2
9          OP  2014-01-01T00:02:10.000       2  35X         2
10         OP  2014-01-01T00:03:10.000       2  29X         2
11         OP  2014-01-01T00:04:13.000       1  06X         2
12         OP  2014-01-01T00:04:34.000       2  23X         2
13         OP  2014-01-01T00:04:48.000       2  32Y         2
14         OP  2014-01-01T00:05:09.000       2  32X         2
15         OP  2014-01-01T00:06:06.000       1  10X         2
16         OP  2014-01-01T00:06:25.000       1  22Y         2
17         OP  2014-01-01T00:06:29.000       2  27X         1
18         OP  2014-01-01T00:06:53.000       1  09X         2
19         OP  2014-01-01T00:06:59.000       1  17Y         2
20         OP  2014-01-01T00:07:04.000       1  05X         1
21         OP  2014-01-01T00:07:36.000       2  27X         2
22         OP  2014-01-01T00:07:38.000       2  31Z         2
23         OP  2014-01-01T00:08:40.000       2  27Y         2
24         OP  2014-01-01T00:09:04.000       2  27Y         2
25         OP  2014-01-01T00:10:05.000       1  15X         2
26         OP  2014-01-01T00:11:55.000       1  09X         2
27         OP  2014-01-01T00:12:40.000       2  25X         2
28         OP  2014-01-01T00:13:20.000       2  35X         2
29         OP  2014-01-01T00:15:29.000       1  13Z         2
...       ...                      ...     ...  ...       ...
187450     OP  2014-10-29T19:01:28.000     1.0  04X         1
187451     OP  2014-10-30T22:00:29.000     1.0  18Y         2
187452     OP  2014-11-03T20:47:30.000     1.0  20X         1
187453     OP  2014-11-03T07:48:56.000     1.0  04X         2
187454     OP  2014-11-03T07:45:01.000     1.0  22Y         2
187455     OP  2014-11-04T18:56:19.000     1.0  24X         2
187456     OP  2014-11-03T20:48:57.000     1.0  24Y         1
187457     OP  2014-11-03T07:39:01.000     1.0  17Y         2
187458     OP  2014-11-03T20:50:20.000     1.0  03X         1
187459     OP  2014-11-13T12:09:58.000     1.0  35X         2
187460     OP  2014-11-12T12:02:25.000     1.0  06X         2
187461     OP  2014-11-12T12:01:53.000     1.0  29X         2
187462     OP  2014-11-08T22:42:49.000     1.0  04X         2
187463     OP  2014-11-08T22:44:40.000     1.0  12Y         2
187464     OP  2014-11-09T11:28:01.000     1.0  04X         1
187465     OP  2014-11-26T21:22:03.000     1.0  27Y         1
187466     OP  2014-11-26T21:23:46.000     1.0  21X         2
187467     OP  2014-11-13T12:11:22.000     1.0  21X         2
187468     OP  2014-11-14T08:00:06.000     1.0  35Y         2
187469     OP  2014-11-14T13:35:31.000     1.0  13X         2
187470     OP  2014-11-19T12:14:19.000     1.0  04X         2
187471     OP  2014-11-18T18:30:13.000     1.0  08X         1
187472     OP  2014-11-18T13:00:39.000     1.0  06X         1
187473     OP  2014-11-21T20:12:14.000     1.0  04X         2
187474     OP  2014-11-21T09:01:50.000     1.0  08X         2
187475     OP  2014-12-30T05:59:53.000     1.0  07X         1
187476     OP  2014-10-28T21:05:21.000     1.0  02X         1
187477     OP  2014-11-03T07:14:40.000     1.0  23X         2
187478     OP  2014-10-20T09:45:52.000     1.0  16Y         1
187479     OP  2014-11-12T01:30:19.000     1.0  07X         2

       Incident Type Id Incident Type Description     Event Number  \
0                 415GS              415 GUNSHOTS  LOP140101000001
1                 415GS              415 GUNSHOTS  LOP140101000002
2                 415GS              415 GUNSHOTS  LOP140101000004
3                 415GS              415 GUNSHOTS  LOP140101000005
4                 CODE7      SUBJECT ARMED WITH W  LOP140101000010
5                 415GS              415 GUNSHOTS  LOP140101000006
6                 415GS              415 GUNSHOTS  LOP140101000007
7                  911H               911 HANG-UP  LOP140101000008
8                 415GS              415 GUNSHOTS  LOP140101000009
9                 415GS              415 GUNSHOTS  LOP140101000011
10                415GS              415 GUNSHOTS  LOP140101000017
11                  247       SHOOTING AT/INTO AN  LOP140101000014
12                415GS              415 GUNSHOTS  LOP140101000012
13                415GS              415 GUNSHOTS  LOP140101000013
14                415GS              415 GUNSHOTS  LOP140101000015
15                 933R              ALARM-RINGER  LOP140101000016
16                 911H               911 HANG-UP  LOP140101000018
17                CODE7      SUBJECT ARMED WITH W  LOP140101000024
18                 933R              ALARM-RINGER  LOP140101000023
19                 415C               415 UNKNOWN  LOP140101000019
20                  929                      FIRE  LOP140101000020
21                415GS              415 GUNSHOTS  LOP140101000021
22                415GS              415 GUNSHOTS  LOP140101000022
23                415GS              415 GUNSHOTS  LOP140101000027
24                415GS              415 GUNSHOTS  LOP140101000025
25                415GS              415 GUNSHOTS  LOP140101000026
26                415GS              415 GUNSHOTS  LOP140101000028
27                  912         SUSPICIOUS PERSON  LOP140101000032
28                415GS              415 GUNSHOTS  LOP140101000033
29                  HAZ      HAZARDOUS SITUATION/  LOP140101000039
...                 ...                       ...              ...
187450              943                     FIGHT  LOP141029001022
187451              922       DRUNK ON THE STREET  LOP141030001083
187452             PDOA      POSSIBLE DEAD PERSON  LOP141103000917
187453           HYDRNT              OPEN HYDRANT  LOP141103000175
187454             601I      INCORRIGIBLE: BEYOND  LOP141103000173
187455            415BF             415 BOYFRIEND  LOP141104000927
187456             SUSP                   SUSPECT  LOP141103000918
187457             955A            VICIOUS ANIMAL  LOP141103000171
187458              918          PERSON SCREAMING  LOP141103000920
187459             955A            VICIOUS ANIMAL  LOP141113000497
187460             5150              MENTALLY ILL  LOP141112000450
187461             933R              ALARM-RINGER  LOP141112000448
187462            415GS              415 GUNSHOTS  LOP141108001015
187463             415C               415 UNKNOWN  LOP141108001017
187464              945       AMBULANCE FOLLOW UP  LOP141109000388
187465              910           PROWLER OUTSIDE  LOP141126000831
187466            10851            STOLEN VEHICLE  LOP141126000833
187467            20002       HIT & RUN (PROPERTY  LOP141113000498
187468             EVID                  EVIDENCE  LOP141114000216
187469             933R              ALARM-RINGER  LOP141114000556
187470             911H               911 HANG-UP  LOP141119000513
187471            10851            STOLEN VEHICLE  LOP141118000926
187472              487               GRAND THEFT  LOP141118000528
187473             911H               911 HANG-UP  LOP141121000998
187474              975      STAND BY AND PRESERV  LOP141121000318
187475              929                      FIRE  LOP141230000166
187476              245      ASSAULT W/DEADLY WEA  LOP141028001057
187477              HAZ      HAZARDOUS SITUATION/  LOP141103000159
187478             901A      VEHICLE COLLISION-PE  LOP141020000319
187479              240                   ASSAULT  LOP141112000046

                    Closed Time  \
0       2014-01-01T03:22:08.000
1       2014-01-01T02:56:31.000
2       2014-01-01T00:49:53.000
3       2014-01-01T02:51:11.000
4       2014-01-01T05:33:22.000
5       2014-01-01T03:53:57.000
6       2014-01-01T00:01:32.000
7       2014-01-01T08:23:08.000
8       2014-01-01T03:30:10.000
9       2014-01-01T10:35:45.000
10      2014-01-01T03:08:48.000
11      2014-01-01T11:43:10.000
12      2014-01-01T03:23:00.000
13      2014-01-01T02:46:17.000
14      2014-01-01T00:11:30.000
15      2014-01-01T07:38:34.000
16      2014-01-01T00:10:25.000
17      2014-01-01T00:24:49.000
18      2014-01-01T04:37:57.000
19      2014-01-01T08:09:33.000
20      2014-01-01T00:08:34.000
21      2014-01-01T06:58:13.000
22      2014-01-01T11:52:45.000
23      2014-01-01T03:43:12.000
24      2014-01-01T03:23:54.000
25      2014-01-01T03:47:23.000
26      2014-01-01T03:23:09.000
27      2014-01-01T00:53:06.000
28      2014-01-01T01:24:42.000
29      2014-01-01T02:08:09.000
...                         ...
187450  2014-10-29T19:01:28.000
187451  2014-10-30T22:35:49.000
187452  2014-11-03T22:27:40.000
187453  2014-11-03T07:48:59.000
187454  2014-11-03T09:44:38.000
187455  2014-11-04T22:56:39.000
187456  2014-11-04T02:07:27.000
187457  2014-11-03T13:54:44.000
187458  2014-11-03T21:05:45.000
187459  2014-11-14T11:01:10.000
187460  2014-11-12T12:36:13.000
187461  2014-11-12T12:03:38.000
187462  2014-11-08T23:21:41.000
187463  2014-11-08T22:53:11.000
187464  2014-11-09T11:38:51.000
187465  2014-11-26T22:02:19.000
187466  2014-11-26T23:34:56.000
187467  2014-11-13T13:19:11.000
187468  2014-11-14T08:36:54.000
187469  2014-11-14T16:17:03.000
187470  2014-11-19T12:15:59.000
187471  2014-11-18T19:57:31.000
187472  2014-11-18T15:18:42.000
187473  2014-11-21T20:33:14.000
187474  2014-11-21T11:26:21.000
187475  2014-12-30T05:59:53.000
187476  2014-10-28T22:53:01.000
187477  2014-11-03T09:00:40.000
187478  2014-10-20T12:07:29.000
187479  2014-11-12T02:14:09.000

                                               Location 1  Zip Codes
0       {'human_address': '{"address": "LINDEN ST", "c...        NaN
1       {'human_address': '{"address": "AV&INTERNATION...        NaN
2       {'human_address': '{"address": "AV&MACARTHUR B...        NaN
3       {'human_address': '{"address": "MACARTHUR BLVD...        NaN
4       {'human_address': '{"address": "AV&DOWLING ST"...        NaN
5       {'human_address': '{"address": "AV&INTERNATION...        NaN
6       {'human_address': '{"address": "AV&PIPPIN ST",...        NaN
7       {'human_address': '{"address": "E 16TH ST", "c...        NaN
8       {'human_address': '{"address": "ST&WILLOW ST",...        NaN
9       {'human_address': '{"address": "86TH AV", "cit...        NaN
10      {'human_address': '{"address": "AV&MACARTHUR B...        NaN
11      {'human_address': '{"address": "MARTIN LUTHER ...        NaN
12      {'human_address': '{"address": "AV&INTERNATION...        NaN
13      {'human_address': '{"address": "MACARTHUR BLVD...        NaN
14      {'human_address': '{"address": "AV&ROYAL ANN S...        NaN
15      {'human_address': '{"address": "59TH ST", "cit...        NaN
16      {'human_address': '{"address": "MACARTHUR BLVD...        NaN
17      {'human_address': '{"address": "47TH AV", "cit...        NaN
18      {'human_address': '{"address": "HOWE ST", "cit...        NaN
19      {'human_address': '{"address": "10TH AV", "cit...        NaN
20      {'human_address': '{"address": "GRAND AV&MARKE...        NaN
21      {'human_address': '{"address": "AV&SAN CARLOS ...        NaN
22      {'human_address': '{"address": "MOORPARK AV", ...        NaN
23      {'human_address': '{"address": "AV&SEMINARY AV...        NaN
24      {'human_address': '{"address": "AV&WENTWORTH A...        NaN
25      {'human_address': '{"address": "MACARTHUR BLVD...        NaN
26      {'human_address': '{"address": "W MACARTHUR BL...        NaN
27      {'human_address': '{"address": "39TH AV", "cit...        NaN
28      {'human_address': '{"address": "83RD AV", "cit...        NaN
29      {'human_address': '{"address": "BLVD&PARK BLVD...        NaN
...                                                   ...        ...
187450  {'latitude': '42.777598', 'longitude': '-86.10...    12476.0
187451  {'latitude': '39.317858', 'longitude': '-76.61...    27307.0
187452  {'latitude': '30.225607', 'longitude': '-92.37...    21181.0
187453  {'latitude': '27.222444', 'longitude': '-80.39...    11199.0
187454  {'latitude': '45.76034', 'longitude': '-108.51...    23276.0
187455  {'latitude': '43.129903', 'longitude': '-77.65...    27347.0
187456  {'latitude': '27.668478', 'longitude': '-80.42...    22280.0
187457  {'latitude': '37.416078', 'longitude': '-122.1...      315.0
187458  {'latitude': '45.460189', 'longitude': '-98.47...    27204.0
187459  {'latitude': '42.57794', 'longitude': '-87.912...    12442.0
187460  {'latitude': '36.825804', 'longitude': '-119.7...    27979.0
187461  {'latitude': '41.699832', 'longitude': '-70.58...      420.0
187462  {'latitude': '42.290689', 'longitude': '-71.40...    22816.0
187463  {'latitude': '21.282438', 'longitude': '-157.7...     7526.0
187464  {'latitude': '34.299407', 'longitude': '-85.00...    23486.0
187465  {'latitude': '33.019627', 'longitude': '-96.70...     4560.0
187466  {'latitude': '32.66655', 'longitude': '-117.09...    10453.0
187467  {'latitude': '41.457702', 'longitude': '-84.88...     5080.0
187468  {'latitude': '37.217435', 'longitude': '-121.8...    11854.0
187469  {'latitude': '42.370496', 'longitude': '-71.10...    16547.0
187470  {'latitude': '18.383182', 'longitude': '-65.84...    26722.0
187471  {'latitude': '42.472465', 'longitude': '-71.02...     7894.0
187472  {'latitude': '39.942248', 'longitude': '-75.17...     3680.0
187473  {'latitude': '31.223089', 'longitude': '-81.84...    32748.0
187474  {'latitude': '41.676273', 'longitude': '-85.98...    22736.0
187475  {'latitude': '40.664095', 'longitude': '-73.66...    26004.0
187476  {'latitude': '34.128805', 'longitude': '-79.82...    27099.0
187477  {'latitude': '27.917761', 'longitude': '-82.51...     7967.0
187478  {'latitude': '40.774561', 'longitude': '-73.90...    16862.0
187479  {'latitude': '37.953895', 'longitude': '-121.2...    12234.0

[187480 rows x 11 columns]

#### 3. 根据数据对象的相似性来填充数据值

   这里我们使用的是KNN算法，实体之间的距离计算使用曼哈顿距离。K的值设置为6。我们选取与存在空缺值的向量距离最近的6个向量在对应属性上的平均值来对空缺值进行填充。